### ISSUE TITLE
NoClassDefFoundError with maven 3.1.1

### ISSUE THREAD

**Issue by kellyrob99** [klieber/phantomjs-maven-plugin#20]
It looks like in newer maven the plugin's classloader is closed before TrueZip's shutdown hook has a chance to unmount any open files, leading to an exception.

PR #19 contains a proposed fix that works with maven 3.1.1
